[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = time, log2file
build_flags = 
    -D_LED_PIN=23
    -D_LDR_PIN=34
    -D_SAMPLING_MS=200
upload_speed = 921600
